# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('dr_nbr', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('volumes', models.IntegerField(default=1)),
                ('date_reviewed', models.DateTimeField(null=True)),
                ('crime_committed', models.CharField(max_length=32)),
                ('motive', models.CharField(max_length=32)),
                ('court_case_number', models.CharField(max_length=32, null=True)),
                ('coroner_case_number', models.CharField(max_length=32, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_occurred', models.DateTimeField()),
                ('date_reported', models.DateTimeField()),
                ('address', models.CharField(max_length=50)),
                ('weapon', models.CharField(max_length=30, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_edited', models.DateTimeField()),
                ('edited_by', models.CharField(max_length=30)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=30)),
                ('bureau', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=32, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Office'),
        ),
        migrations.AddField(
            model_name='case',
            name='related_cases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
    ]
