# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20171023_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binder',
            fields=[
                ('master_dr', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('check_out_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bureau', models.CharField(max_length=32)),
                ('division', models.CharField(max_length=32)),
                ('reporting_district', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='case',
            old_name='date_reviewed',
            new_name='date_fully_reviewed',
        ),
        migrations.RemoveField(
            model_name='case',
            name='office',
        ),
        migrations.RemoveField(
            model_name='case',
            name='volumes',
        ),
        migrations.AddField(
            model_name='case',
            name='adjudication',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='evidence_destroyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('AA', 'Adult Arrest'), ('JA', 'Juvenile Arrest'), ('AO', 'Adult Other'), ('JO', 'Juvenile Other'), ('IC', 'Investigation Continued')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='status_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='ethnicity',
            field=models.CharField(choices=[('W', 'White'), ('H', 'Hispanic'), ('B', 'Black or African American'), ('A', 'Asian'), ('AI', 'American Indian or Alaska Native'), ('ME', 'Middle Eastern'), ('PI', 'Pacific Islander'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.RemoveField(
            model_name='case',
            name='related_cases',
        ),
        migrations.AddField(
            model_name='case',
            name='related_cases',
            field=models.ManyToManyField(null=True, related_name='_case_related_cases_+', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='event',
            name='weapon',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='edited_by',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.AddField(
            model_name='case',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cases.District'),
            preserve_default=False,
        ),
    ]
