# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20171025_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='related_cases',
            field=models.ManyToManyField(related_name='_case_related_cases_+', to='cases.Case'),
        ),
    ]
