# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20171025_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='cases.District'),
        ),
        migrations.AlterField(
            model_name='event',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='person',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='cases.Case'),
        ),
    ]
