# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20171126_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='victim',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
