# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_person_victim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='case',
        ),
        migrations.RemoveField(
            model_name='person',
            name='victim',
        ),
        migrations.AddField(
            model_name='person',
            name='case_suspect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.Case'),
        ),
        migrations.AddField(
            model_name='person',
            name='case_victim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='cases.Case'),
        ),
    ]
