# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20171127_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='case_suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='person',
            name='case_victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
