# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20171127_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ethnicity',
            field=models.CharField(choices=[('W', 'White'), ('H', 'Hispanic'), ('B', 'Black or African American'), ('A', 'Asian'), ('AI', 'American Indian or Alaska Native'), ('ME', 'Middle Eastern'), ('PI', 'Pacific Islander'), ('O', 'Other')], max_length=2, null=True),
        ),
    ]
