# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_auto_20171128_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='binder',
            field=models.ForeignKey(default='NO_BINDER', on_delete=django.db.models.deletion.CASCADE, to='cases.Binder'),
            preserve_default=False,
        ),
    ]
