# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_case_binder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='binder',
        ),
        migrations.AddField(
            model_name='case',
            name='binders',
            field=models.ManyToManyField(related_name='cases', to='cases.Binder'),
        ),
        migrations.AlterField(
            model_name='case',
            name='suspects',
            field=models.ManyToManyField(blank=True, related_name='suspects', to='cases.Person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='victims',
            field=models.ManyToManyField(blank=True, related_name='victims', to='cases.Person'),
        ),
    ]
