# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_auto_20171129_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='binders',
            field=models.ManyToManyField(blank=True, related_name='cases', to='cases.Binder'),
        ),
    ]
