# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_auto_20171129_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binder',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='adjudication',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_case_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_fully_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='motive',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, choices=[('AA', 'Adult Arrest'), ('JA', 'Juvenile Arrest'), ('AO', 'Adult Other'), ('JO', 'Juvenile Other'), ('IC', 'Investigation Continued')], default='NA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='coroner_case_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='crime_committed',
            field=models.CharField(blank=True, choices=[('M', 'Murder')], default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_occurred',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_reported',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='weapon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('W', 'White'), ('H', 'Hispanic'), ('B', 'Black or African American'), ('A', 'Asian'), ('AI', 'American Indian or Alaska Native'), ('ME', 'Middle Eastern'), ('PI', 'Pacific Islander'), ('O', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
