# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_auto_20171202_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, choices=[('AA', 'Adult Arrest'), ('JA', 'Juvenile Arrest'), ('AO', 'Adult Other'), ('JO', 'Juvenile Other'), ('IC', 'Investigation Continued')], max_length=2, null=True),
        ),
    ]
