# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_auto_20171202_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_fully_reviewed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
