# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_auto_20171203_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_occurred',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_reported',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_edited',
            field=models.DateField(),
        ),
    ]
