# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_auto_20171203_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binder',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
