# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_auto_20171203_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='adjudication',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
